# Generated by Django 5.1.2 on 2025-03-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_commercial_reports', 'Can view commercial reports'), ('can_edit_commercial_reports', 'Can edit commercial reports'), ('can_view_sales_data', 'Can view sales data'), ('can_manage_commercial_team', 'Can manage commercial team'), ('can_view_support_tickets', 'Can view support tickets'), ('can_edit_support_tickets', 'Can edit support tickets'), ('can_manage_support_team', 'Can manage support team'), ('can_view_installation_tasks', 'Can view installation tasks'), ('can_edit_installation_tasks', 'Can edit installation tasks'), ('can_manage_installation_team', 'Can manage installation team'), ('can_view_marketing_campaigns', 'Can view marketing campaigns'), ('can_edit_marketing_campaigns', 'Can edit marketing campaigns'), ('can_manage_marketing_team', 'Can manage marketing team'), ('can_view_infrastructure', 'Can view infrastructure'), ('can_edit_infrastructure', 'Can edit infrastructure'), ('can_manage_infrastructure_team', 'Can manage infrastructure team'), ('can_view_it_projects', 'Can view IT projects'), ('can_edit_it_projects', 'Can edit IT projects'), ('can_manage_it_team', 'Can manage IT team'), ('can_view_billing', 'Can view billing'), ('can_edit_billing', 'Can edit billing'), ('can_manage_billing_team', 'Can manage billing team'), ('can_view_financial_reports', 'Can view financial reports'), ('can_edit_financial_reports', 'Can edit financial reports'), ('can_manage_financial_team', 'Can manage financial team'), ('can_view_collections', 'Can view collections'), ('can_edit_collections', 'Can edit collections'), ('can_view_receivables', 'Can view receivables'), ('can_edit_receivables', 'Can edit receivables'), ('can_view_all_reports', 'Can view all reports'), ('can_manage_all_teams', 'Can manage all teams')]},
        ),
    ]
