# Generated by Django 5.1.2 on 2025-03-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_commercial_reports', 'Pode ver relatórios comerciais'), ('can_edit_commercial_reports', 'Pode editar relatórios comerciais'), ('can_view_sales_data', 'Pode ver dados de vendas'), ('can_manage_commercial_team', 'Pode gerenciar equipe comercial'), ('can_view_support_tickets', 'Pode ver tickets de suporte'), ('can_edit_support_tickets', 'Pode editar tickets de suporte'), ('can_manage_support_team', 'Pode gerenciar equipe de suporte'), ('can_view_installation_tasks', 'Pode ver tarefas de instalação'), ('can_edit_installation_tasks', 'Pode editar tarefas de instalação'), ('can_manage_installation_team', 'Pode gerenciar equipe de instalação'), ('can_view_marketing_campaigns', 'Pode ver campanhas de marketing'), ('can_edit_marketing_campaigns', 'Pode editar campanhas de marketing'), ('can_manage_marketing_team', 'Pode gerenciar equipe de marketing'), ('can_view_infrastructure', 'Pode ver infraestrutura'), ('can_edit_infrastructure', 'Pode editar infraestrutura'), ('can_manage_infrastructure_team', 'Pode gerenciar equipe de infraestrutura'), ('can_view_it_projects', 'Pode ver projetos de TI'), ('can_edit_it_projects', 'Pode editar projetos de TI'), ('can_manage_it_team', 'Pode gerenciar equipe de TI'), ('can_view_billing', 'Pode ver faturamento'), ('can_edit_billing', 'Pode editar faturamento'), ('can_manage_billing_team', 'Pode gerenciar equipe de faturamento'), ('can_view_financial_reports', 'Pode ver relatórios financeiros'), ('can_edit_financial_reports', 'Pode editar relatórios financeiros'), ('can_manage_financial_team', 'Pode gerenciar equipe financeira'), ('can_view_collections', 'Pode ver cobranças'), ('can_edit_collections', 'Pode editar cobranças'), ('can_view_receivables', 'Pode ver contas a receber'), ('can_edit_receivables', 'Pode editar contas a receber'), ('can_view_all_reports', 'Pode ver todos os relatórios'), ('can_manage_all_teams', 'Pode gerenciar todas as equipes')]},
        ),
    ]
