# Generated by Django 5.1.2 on 2025-03-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('pode_ver_relatorios_comerciais', 'Pode ver relatórios comerciais'), ('pode_editar_relatorios_comerciais', 'Pode editar relatórios comerciais'), ('pode_ver_dados_vendas', 'Pode ver dados de vendas'), ('pode_gerenciar_equipe_comercial', 'Pode gerenciar equipe comercial'), ('pode_ver_tickets_suporte', 'Pode ver tickets de suporte'), ('pode_editar_tickets_suporte', 'Pode editar tickets de suporte'), ('pode_gerenciar_equipe_suporte', 'Pode gerenciar equipe de suporte'), ('pode_ver_tarefas_instalacao', 'Pode ver tarefas de instalação'), ('pode_editar_tarefas_instalacao', 'Pode editar tarefas de instalação'), ('pode_gerenciar_equipe_instalacao', 'Pode gerenciar equipe de instalação'), ('pode_ver_campanhas_marketing', 'Pode ver campanhas de marketing'), ('pode_editar_campanhas_marketing', 'Pode editar campanhas de marketing'), ('pode_gerenciar_equipe_marketing', 'Pode gerenciar equipe de marketing'), ('pode_ver_infraestrutura', 'Pode ver infraestrutura'), ('pode_editar_infraestrutura', 'Pode editar infraestrutura'), ('pode_gerenciar_equipe_infraestrutura', 'Pode gerenciar equipe de infraestrutura'), ('pode_ver_projetos_ti', 'Pode ver projetos de TI'), ('pode_editar_projetos_ti', 'Pode editar projetos de TI'), ('pode_gerenciar_equipe_ti', 'Pode gerenciar equipe de TI'), ('pode_ver_faturamento', 'Pode ver faturamento'), ('pode_editar_faturamento', 'Pode editar faturamento'), ('pode_gerenciar_equipe_faturamento', 'Pode gerenciar equipe de faturamento'), ('pode_ver_relatorios_financeiros', 'Pode ver relatórios financeiros'), ('pode_editar_relatorios_financeiros', 'Pode editar relatórios financeiros'), ('pode_gerenciar_equipe_financeira', 'Pode gerenciar equipe financeira'), ('pode_ver_cobrancas', 'Pode ver cobranças'), ('pode_editar_cobrancas', 'Pode editar cobranças'), ('pode_ver_contas_receber', 'Pode ver contas a receber'), ('pode_editar_contas_receber', 'Pode editar contas a receber'), ('pode_ver_todos_relatorios', 'Pode ver todos os relatórios'), ('pode_gerenciar_todas_equipes', 'Pode gerenciar todas as equipes')]},
        ),
    ]
