# Generated by Django 5.1.2 on 2025-03-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_remove_user_cpf'),
        ('custom_user', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
