# Generated by Django 5.1.2 on 2025-03-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('admin', 'Pode gerenciar grupos e usuários'), ('atendimento', 'Acesso ao dashboard de atendimento'), ('direcao', 'Acesso ao dashboard da direção'), ('faturamento', 'Acesso ao dashboard de faturamento'), ('financeiro', 'Acesso ao dashboard financeiro'), ('infraestrutura', 'Acesso ao dashboard da infraestrutura'), ('instalacao', 'Acesso ao dashboard da instalação'), ('marketing', 'Acesso ao dashboard de marketing'), ('vendas', 'Pode vizualizar dashboard de vendas'), ('ti', 'Pode vizualizar dashboards de ti')]},
        ),
    ]
